# DO NOT MODIFY THIS FILE!
# THIS FILE WAS AUTOGENERATED BY ISESTEROIDS AND WILL BE OVERWRITTEN WHEN YOU EXPORT FUNCTIONS TO THIS MODULE.

# USE THIS FILE FOR ADDITIONAL MODULE CODE. THIS FILE WILL NOT BE OVERWRITTEN
# WHEN NEW CONTENT IS PUBLISHED TO THIS MODULE:
. $PSScriptRoot\init.ps1


# LOADING ALL FUNCTION DEFINITIONS:

. $PSScriptRoot\Backup-BCDStore.ps1
. $PSScriptRoot\Copy-BcdEntry.ps1
. $PSScriptRoot\Get-BCDCurrentOSGuid.ps1
. $PSScriptRoot\Get-BCDEntry.ps1
. $PSScriptRoot\Get-BCDFirmWareType.ps1
. $PSScriptRoot\Get-BCDLanguage.ps1
. $PSScriptRoot\Get-BCDStore.ps1
. $PSScriptRoot\New-BCDEntry.ps1
. $PSScriptRoot\New-BCDStore.ps1
. $PSScriptRoot\Remove-BcdEntry.ps1
. $PSScriptRoot\Set-BCDDefaultOS.ps1
. $PSScriptRoot\Set-BcdEntry.ps1
. $PSScriptRoot\Show-BCDWellKnownGuids.ps1
. $PSScriptRoot\Test-BCDWinPE.ps1
